language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6

jobs:
  include:
    - stage: gem release
      rvm: 2.5
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        gem: kitchen-yansible
        api_key: $RUBYGEMS_APIKEY
        on:
          branch: master
          tags: true
